### ISSUE TITLE
Review website and test functionality

### ISSUE THREAD

**Issue by camiwins** [choco-taco/space-dashboard#10]
**REMEMBER: Test BOTH index.html and dashboard.html**

DESKTOP (Chrome, Firefox, Safari)
- [x] Does launch button work?
- [x] Do the main nav buttons work?
- [x] Does the map work?
- [x] Enter sol dates for Rover photos and make sure pics display
- [x] Do asteroids date box and prev/next buttons work?
- [x] Does the Space X buttons anchor properly?
- [x] Is the Space X counter working?
- [x] Doest the 'back to top' button work?

MOBILE (iPad and iPhone sizes)
- [x] Does launch button work?
- [x] Do the main nav buttons work?
- [ ] Does the map work?
- [x] Enter sol dates for Rover photos and make sure pics display
- [x] Do asteroids date box and prev/next buttons work?
- [x] Is the Space X counter working?
- [x] Does the Space X buttons anchor properly?
- [x] Doest the 'back to top' button work?

**Comment by capp85** [comment]
everything works!!
